# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc713afd540048283e925dba118fbd7da95655b7921612ccb1a29cf333b7b92ccee93acfff8bd2e4083906ec9b2a8a1f13f10746af25d01105692f5d4e20be4

test:
  secret_key_base: 3234fa00dd8900edea43dd67317c703ea1c6c6c26c744b410c4618dbac4cecc1eaaac41506f15633df338606a86615dd338cacd6c3e647f4d84c154c5b0aed60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
